#!/usr/bin/env node
/**
 * Generate src/version.ts from package.json so source code can reference the
 * package's declared version without hardcoding it. Run as the prebuild step.
 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(REPO_ROOT, 'package.json'), 'utf-8'));
const out = `// This file is generated by scripts/generate-version.js.
// Do not edit by hand — change package.json and rebuild.
export const VERSION = ${JSON.stringify(pkg.version)};
`;
writeFileSync(join(REPO_ROOT, 'src', 'version.ts'), out, 'utf-8');
